# Generated by Django 4.0.6 on 2022-07-10 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created timestamp"
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last update timestamp"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "get_latest_by": "last_updated_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created timestamp"
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last update timestamp"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "get_latest_by": "last_updated_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MediumType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created timestamp"
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last update timestamp"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "get_latest_by": "last_updated_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created timestamp"
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last update timestamp"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "get_latest_by": "last_updated_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created timestamp"
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last update timestamp"
                    ),
                ),
                ("score", models.FloatField()),
            ],
            options={
                "get_latest_by": "last_updated_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created timestamp"
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last update timestamp"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testapp.book"
                    ),
                ),
                (
                    "medium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.mediumtype",
                    ),
                ),
            ],
            options={
                "get_latest_by": "last_updated_at",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="testapp.genre",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="mediums",
            field=models.ManyToManyField(
                through="testapp.Price", to="testapp.mediumtype"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="testapp.publication"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="testapp.rating",
            ),
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created timestamp"
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last update timestamp"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("books", models.ManyToManyField(to="testapp.book")),
            ],
            options={
                "get_latest_by": "last_updated_at",
                "abstract": False,
            },
        ),
    ]
